import {S} from './state.js';
import {icon,esc,num,money,dateISO,dateLabel,duration,btn,iconBtn,field,select,textarea,formFoot,badge,modal,stat} from './ui.js';
import {goals,levels,muscles,measureNames,isManager} from './views.js';

export const allWorkouts=()=>[...S.data.workouts,...(S.student?.workouts||[]),...S.templates];
export const findWorkout=id=>allWorkouts().find(w=>w.id===id);
export function legal(){modal('Dados e privacidade',`<div class="legal"><h3>ATHEV</h3><p>O aplicativo organiza treinos, agenda e os registros que você informar.</p><h3>Armazenamento e acesso</h3><p>O login é realizado pelo Supabase Auth. Perfil, fichas, histórico, medidas, fotos e alimentação são armazenados no banco do ATHEV. O acesso depende da sua conta e das permissões atribuídas pela administração.</p><h3>Suas escolhas</h3><p>Você pode editar seu perfil, exportar seus registros e solicitar a exclusão da conta à administração. Para redefinir a senha, use o link enviado ao seu e-mail.</p><h3>Serviços</h3><p>Pagamentos, catraca e IA generativa dependem de integrações adicionais. Os registros financeiros não realizam cobrança bancária.</p></div>`,true);}

export function exerciseDetail(id,tab='execution'){
 const e=S.data.exercises.find(e=>e.id===id);if(!e)return;
 S.guide={id:e.id,index:0,playing:false,tab};
 const steps=e.instructions.split('|');
 modal(esc(e.name),`<div class="between"><span class="badge badge-gold">${esc(e.muscle)} · ${esc(e.equipment)}</span><button class="icon-btn ${S.data.favorites.includes(e.id)?'active':''}" data-action="favorite-detail" data-id="${e.id}" aria-label="Favoritar exercício">${icon('star')}</button></div><div class="tabs section-gap">${[['execution','Execução'],['muscles','Músculos'],['guide','Guia animado']].map(([k,l])=>`<button class="tab ${tab===k?'active':''}" data-action="exercise-tab" data-id="${e.id}:${k}">${l}</button>`).join('')}</div>${tab==='execution'?`<ol class="instruction-steps">${steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="notice section-gap"><strong>Dica de execução</strong><br>${esc(e.tip)}</div><div class="notice section-gap"><strong>Erro comum</strong><br>${esc(e.mistake)}</div>`:tab==='muscles'?`<div class="muscle-map">${icon('activity')}<div><div class="eyebrow">GRUPO PRINCIPAL</div><h2 style="margin:0">${esc(e.muscle)}</h2><small>${esc(e.equipment)}</small></div></div><p class="tiny muted section-gap">Outros músculos podem participar conforme a variação e a execução. Confirme a técnica com seu professor.</p>`:`<div class="guide-stage" id="guide-stage"><span class="step-number" id="guide-number">PASSO 1 DE ${steps.length}</span><p id="guide-text">${esc(steps[0])}</p></div><div class="between">${btn('Anterior','guide-prev','','secondary','left')}${btn('Reproduzir','guide-play','','primary','play')}${btn('Próximo','guide-next','','secondary','right')}</div><p class="tiny muted section-gap">Guia textual animado. Não representa uma demonstração biomecânica em vídeo.</p>`}<div class="modal-foot">${btn('Entendi','close','','primary','check')}</div>`);
}

export function workoutDetail(id){const w=findWorkout(id);if(!w)return;modal(esc(w.name)+' · '+esc(w.muscle),`<div class="row wrap">${badge(w.level)}${badge(w.duration+' min')}${badge(w.items.length+' exercícios')}</div><p class="tiny muted section-gap">${esc(w.notes)}</p>${w.items.map((e,i)=>`<div class="exercise-row"><span class="exercise-index">${i+1}</span><div class="exercise-info"><strong>${esc(e.name)}</strong><small>${e.sets} × ${e.reps} · ${num(e.weight)} kg · descanso ${e.rest}s<br>${esc(e.technique)}${e.notes?' · '+esc(e.notes):''}</small></div>${iconBtn('play','exercise',e.exercise_id,'Ver execução')}</div>`).join('')}<div class="modal-foot">${btn('Editar ficha','workout-edit',w.id,'secondary','edit')}${w.user_id===S.user.id?btn('Iniciar treino','start',w.id,'primary','play'):''}</div>`);}

export function newEditor(w=null,owner=S.user.id,isTemplate=false){S.editor=w?structuredClone(w):{name:isTemplate?'Template · Novo treino':'Treino A',muscle:'Peito + Tríceps',day:0,duration:60,level:'Intermediário',notes:'',user_id:owner,is_template:isTemplate,items:[{exercise_id:S.data.exercises[0]?.id,sets:3,reps:10,weight:0,rest:60,technique:'Tradicional',notes:''}]};editorView();}
export function readEditor(){const f=document.querySelector('#workout-form');if(!f)return S.editor;const data=Object.fromEntries(new FormData(f));for(const key of ['name','muscle','day','duration','level','notes'])S.editor[key]=data[key];S.editor.items=[...f.querySelectorAll('.editor-item')].map((row,i)=>{const get=k=>f.querySelector(`[name="${k}-${i}"]`).value;return {exercise_id:get('exercise'),sets:Number(get('sets')),reps:Number(get('reps')),weight:Number(get('weight')),rest:Number(get('rest')),technique:get('technique'),notes:get('itemnote')};});return S.editor;}
export function editorView(){const w=S.editor;modal(w.id?'Editar ficha':'Montar treino',`<form id="workout-form"><div class="form-row">${field('Nome da ficha','name',w.name,'text','required maxlength="100"')}${field('Foco / grupos musculares','muscle',w.muscle,'text','required maxlength="100"')}</div><div class="form-row">${select('Dia programado','day',[['0','Segunda'],['1','Terça'],['2','Quarta'],['3','Quinta'],['4','Sexta'],['5','Sábado'],['6','Domingo']],w.day)}${select('Nível','level',levels,w.level)}</div>${field('Duração estimada (minutos)','duration',w.duration,'number','required min="5" max="300"')}<h3 class="section-title">Exercícios da ficha</h3>${w.items.map((e,i)=>`<div class="editor-item">${select('Exercício','exercise-'+i,S.data.exercises.map(x=>[x.id,x.name]),e.exercise_id)}${field('Séries','sets-'+i,e.sets,'number','required min="1" max="20"')}${field('Reps','reps-'+i,e.reps,'number','required min="1" max="1000"')}${field('Kg','weight-'+i,e.weight,'number','required min="0" max="1500" step="0.5"')}${field('Pausa (s)','rest-'+i,e.rest,'number','required min="0" max="600"')}<button type="button" class="icon-btn" data-action="editor-remove" data-id="${i}" aria-label="Remover exercício">${icon('trash')}</button></div><div class="editor-extra">${select('Técnica','technique-'+i,['Tradicional','Drop-set','Bi-set','Rest-pause','Pirâmide','Superset'],e.technique)}${field('Observação','itemnote-'+i,e.notes||'','text','maxlength="1500"')}</div>`).join('')}<button class="btn btn-secondary section-gap" type="button" data-action="editor-add">${icon('plus')}Adicionar exercício</button><div class="section-gap">${textarea('Observações da ficha','notes',w.notes||'','maxlength="2000"')}</div><p class="form-error" role="alert"></p><div class="editor-actions"><button class="btn btn-secondary" type="button" data-action="close">Cancelar</button><button class="btn btn-primary">Salvar ficha ${icon('check')}</button></div></form>`,true);}

export function measurementForm(owner=S.user.id){modal('Registrar evolução corporal',`<form id="measurement-form"><input type="hidden" name="user_id" value="${owner}">${field('Data da avaliação','date',dateISO(),'date','required max="'+dateISO()+'"')}<div class="measure-grid">${Object.entries(measureNames).map(([k,v])=>field(v+' ('+(k==='weight'?'kg':k==='fat'?'%':'cm')+')',k,'','number',`min="0.1" max="${k==='fat'?100:500}" step="0.1"`)).join('')}</div><div class="section-gap">${textarea('Observações','notes','','maxlength="1500"')}</div>${formFoot('Salvar medidas')}</form>`);}
export function eventForm(ev=null,owner=S.user.id){modal(ev?'Reagendar atividade':'Agendar atividade',`<form id="event-form" data-id="${ev?.id||''}"><input type="hidden" name="user_id" value="${owner}">${field('Atividade','title',ev?.title||'','text','required maxlength="120" placeholder="Ex.: Treino A"')}${select('Tipo','kind',['Treino','Descanso','Avaliação','Consulta com personal','Outro'],ev?.kind||'Treino')}${field('Data e hora','starts_at',ev?.starts_at?.slice(0,16)||((S.selectedDate||dateISO())+'T18:00'),'datetime-local','required')}${textarea('Observação','notes',ev?.notes||'','maxlength="1000"')}${formFoot('Salvar na agenda')}</form>`);}
export function photoForm(){modal('Adicionar foto de evolução',`<form id="photo-form">${field('Data','date',dateISO(),'date','required max="'+dateISO()+'"')}${select('Ângulo','angle',['Frente','Lado','Costas'])}${field('Foto (JPG, PNG ou WebP)','image','','file','required accept="image/jpeg,image/png,image/webp"')}<p class="tiny muted">A imagem será reduzida no navegador antes de ser salva no seu banco do ATHEV.</p>${formFoot('Salvar foto')}</form>`);}
export function foodForm(){modal('Registrar refeição',`<form id="food-form">${select('Refeição','meal',['Café da manhã','Lanche da manhã','Almoço','Pré-treino','Pós-treino','Jantar','Ceia'])}${field('Alimentos e porção consumida','food','','text','required maxlength="200" placeholder="Ex.: Arroz 100g, feijão 80g e frango 120g"')}<div class="form-row">${field('Calorias (kcal)','calories','','number','required min="0" max="20000" step="0.1"')}${field('Proteínas (g)','protein','','number','required min="0" max="20000" step="0.1"')}</div><div class="form-row">${field('Carboidratos (g)','carbs','','number','required min="0" max="20000" step="0.1"')}${field('Gorduras (g)','fat','','number','required min="0" max="20000" step="0.1"')}</div><p class="tiny muted">Informe os valores da porção consumida, com base no rótulo ou orientação profissional.</p>${formFoot('Adicionar ao diário')}</form>`);}
export function nutritionGoals(){const g=S.data.user.nutrition_goals;modal('Metas nutricionais',`<form id="nutrition-goals-form"><div class="notice" style="margin-bottom:18px">Insira suas metas definidas com o profissional que acompanha você.</div><div class="form-row">${field('Calorias (kcal)','calories',g.calories,'number','required min="1" max="15000"')}${field('Proteínas (g)','protein',g.protein,'number','required min="1" max="15000"')}</div><div class="form-row">${field('Carboidratos (g)','carbs',g.carbs,'number','required min="1" max="15000"')}${field('Gorduras (g)','fat',g.fat,'number','required min="1" max="15000"')}</div>${field('Água (ml)','water',g.water,'number','required min="1" max="15000"')}${field('Profissional responsável (opcional)','professional',S.data.user.professional||'','text','maxlength="180" placeholder="Nome e registro informado pelo profissional"')}${formFoot('Salvar metas')}</form>`);}
export function profileForm(){const u=S.data.user;modal('Editar meu perfil',`<form id="profile-form">${field('Nome','name',u.name,'text','required maxlength="80"')}<div class="form-row">${field('Data de nascimento','birth_date',u.birth_date||'','date','max="'+dateISO()+'"')}${select('Sexo (opcional)','sex',['','Feminino','Masculino','Outro','Prefiro não informar'],u.sex||'')}</div><div class="form-row">${field('Peso (kg)','weight',u.weight||'','number','required min="20" max="500" step="0.1"')}${field('Altura (cm)','height',u.height||'','number','required min="60" max="250" step="0.1"')}</div>${select('Objetivo','goal',goals,u.goal)}${select('Experiência','level',levels,u.level)}${formFoot('Salvar perfil')}</form>`);}

export function historyDetail(h){modal('Resumo do treino',`<div class="success"><div class="success-icon">${icon('check')}</div><div class="eyebrow">TREINO CONCLUÍDO</div><h2>${esc(h.name)}</h2><p class="tiny muted">${dateLabel(h.started_at,true)} · ${esc(h.difficulty||'Ideal')}</p><div class="grid grid-4">${stat('Duração',duration(h.duration),'','clock')}${stat('Exercícios',h.summary.exercises,'','dumbbell')}${stat('Séries',h.summary.sets,'','activity')}${stat('Volume',num(h.summary.volume),'kg','weight')}</div></div>${h.items.map(e=>`<div class="exercise-row"><div class="exercise-info"><strong>${esc(e.name)}</strong><small>${e.sets.filter(s=>s.done).map(s=>num(s.weight,1)+' kg × '+s.reps).join(' · ')||'Nenhuma série concluída'}</small></div>${badge(e.sets.filter(s=>s.done).length+' séries','gold')}</div>`).join('')}<p class="tiny muted section-gap">${esc(h.notes||'Sem observações.')}</p><div class="modal-foot">${btn('Fechar','close','','primary')}</div>`,true);}
export function finishForm(){const s=S.data.active;if(!s)return;let completed=s.items.flatMap(e=>e.sets).filter(x=>x.done).length,total=s.items.flatMap(e=>e.sets).length;modal('Finalizar treino',`<form id="finish-form"><div class="success"><div class="success-icon">${icon('trophy')}</div><h2>Mais um passo dado.</h2><p class="muted">Você concluiu ${completed} de ${total} séries.</p>${completed<total?'<p class="tiny muted">Somente as séries marcadas serão registradas nos resultados.</p>':''}<p class="gold">Qual foi a dificuldade de hoje?</p><div class="difficulty">${['Muito fácil','Fácil','Ideal','Difícil','Muito difícil'].map(d=>`<label><input type="radio" name="difficulty" value="${d}" ${d==='Ideal'?'checked':''}><span>${d}</span></label>`).join('')}</div></div>${formFoot('Concluir e salvar')}</form>`);}
export function invoice(p){modal('Fatura ATHEV',`<div class="notice">DOCUMENTO DE DEMONSTRAÇÃO · SEM VALIDADE FISCAL</div><div class="section-gap"><div class="eyebrow">ATHEV PERFORMANCE</div><h2>Fatura #ATH-${String(p.id).padStart(4,'0')}</h2><p class="muted">${esc(S.data.user.name)}</p><div class="settings-row"><span>Vencimento</span><strong>${dateLabel(p.due_date,true)}</strong></div><div class="settings-row"><span>Valor</span><strong class="gold">${money(p.amount)}</strong></div><div class="settings-row"><span>Status</span>${badge(p.status,p.status==='Pago'?'green':'gold')}</div><p class="tiny muted section-gap">Este registro não contém boleto, link de pagamento ou cobrança bancária.</p></div><div class="modal-foot">${btn('Imprimir / salvar PDF','print','','primary','download')}</div>`);}

export function userForm(u=null,role='ALUNO'){
 const d=S.staff;modal(u?'Editar cadastro':'Novo cadastro',`<form id="admin-user-form" data-id="${u?.id||''}">${field('Nome completo','name',u?.name||'','text','required maxlength="80"')}${!u?field('E-mail','email','','email','required'):''}${!u?field('Senha inicial','password','','password','required minlength="8" maxlength="128"'):''}${!u?select('Perfil','role',isManager()&&S.user.role==='ADMIN'?['ALUNO','PROFESSOR','RECEPCIONISTA','GERENTE','ADMIN']:['ALUNO','PROFESSOR','RECEPCIONISTA'],role):''}${select('Plano','plan_id',d.plans.map(p=>[p.id,p.name+' · '+money(p.price)]),u?.plan_id||1)}${u?select('Status do plano','status',['Ativo','Suspenso','Cancelado'],u.status||'Ativo'):''}${(!u||u.role==='ALUNO')?select('Professor responsável (alunos)','trainer_id',[['','Sem vínculo'],...d.users.filter(p=>p.role==='PROFESSOR'&&p.active).map(p=>[p.id,p.name])],d.assignments?.find(a=>a.student_id===u?.id)?.trainer_id||''):''}${!u?'<p class="tiny muted">O usuário deverá registrar o consentimento no próprio perfil. Guarde e entregue o código de recuperação gerado após o cadastro.</p>':''}${formFoot(u?'Salvar cadastro':'Criar cadastro')}</form>`);
}
export function entityForm(type,id=null){
 const source=type==='exercises'?S.data.exercises:S.staff[type],x=source.find(x=>x.id===id)||{};
 let inputs='';
 if(type==='gyms')inputs=field('Nome','name',x.name||'','text','required')+field('Endereço','address',x.address||'','text','required')+field('Horários','hours',x.hours||'','text','required')+field('Telefone','phone',x.phone||'')+textarea('Serviços','services',x.services||'')+textarea('Equipamentos','equipment',x.equipment||'');
 else if(type==='plans')inputs=field('Nome do plano','name',x.name||'','text','required')+field('Mensalidade demonstrativa (R$)','price',x.price??'','number','required min="0" max="100000" step="0.01"')+textarea('Benefícios · separe cada item com |','benefits',x.benefits||'','required');
 else if(type==='classes')inputs=field('Nome da aula','title',x.title||'','text','required')+field('Professor','teacher',x.teacher||'','text','required')+field('Data e hora','starts_at',x.starts_at?.slice(0,16)||dateISO()+'T18:00','datetime-local','required')+`<div class="form-row">${field('Duração (min)','duration',x.duration||50,'number','required min="10" max="300"')}${field('Capacidade','capacity',x.capacity||12,'number','required min="1" max="500"')}</div>`+select('Unidade','gym_id',S.data.gyms.map(g=>[g.id,g.name]),x.gym_id||1)+field('Antecedência mínima para cancelar (min)','cancel_minutes',x.cancel_minutes??60,'number','required min="0" max="10080"');
 else inputs=field('Nome do exercício','name',x.name||'','text','required')+select('Grupo muscular','muscle',muscles.slice(1),x.muscle||'Peito')+field('Equipamento','equipment',x.equipment||'','text','required')+textarea('Passos de execução · separe cada passo com |','instructions',x.instructions||'','required')+textarea('Dica','tip',x.tip||'','required')+textarea('Erro comum','mistake',x.mistake||'','required');
 modal((id?'Editar':'Novo')+' '+({gyms:'cadastro de unidade',plans:'plano',classes:'cadastro de aula',exercises:'exercício'}[type]),`<form id="entity-form" data-type="${type}" data-id="${id||''}">${inputs}${formFoot('Salvar cadastro')}</form>`);
}
